modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Chisel-Team/Chisel/issues/"

[[mods]]
modId="chisel"
version="${file.jarVersion}"
displayName="Chisel"
displayURL="https://chisel.team"
#logoFile="examplemod.png"
credits="AUTOMATIC_MAIDEN, for the original Chisel, and Pokefenn, asie, and Cricket for maintaining it."
authors="tterrag, Drullkus, minecreatr"
description='''
Adds in tons of fancy blocks for decoration, crafted using the Chisel.
'''
