modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Chisel-Team/Chisel/issues/"
license="GPLv2"

[[mods]]
modId="chisel-legacy"
version="${file.jarVersion}"
displayName="Chisel - Legacy"
authors="tterrag"
